name: "Erlang CI"
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dbus python3-gi python3-dbus erlang

    - name: Compile
      run: |
        make
        make -C demo

    - name: Run tests
      run: |
        make eunit
        dbus-run-session --config-file=demo/test/session.conf -- make -C demo eunit

    - name: Run CT
      run: |
        make ct
    - name: Upload ct logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ct_logs
        path: logs
